spring.application.name=demo

# Azure SQL Database 接続設定
spring.datasource.url=jdbc:sqlserver://orange-examdb.database.windows.net:1433;database=examdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;
spring.datasource.username=Cjm5R7WQ@orange-examdb
spring.datasource.password=379mwDrGqvwtx3daNvtT
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate設定
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 日本語文字化け対策の追加設定
spring.sql.init.encoding=UTF-8
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true